---
app_path: "/home/malck/DevOPs/Lab1/AppDir"
repository: "https://github.com/mdn/django-locallibrary-tutorial.git"
docker_image_name: "django_app"
docker_container_name: "django_app"
docker_container_port: "808"
dockerfile_path: "/home/malck/DevOPs/Lab1/Dockerfile"
